feat: 로그인/회원가입 화면 구현
4transcendence2/frontend pull request #11
Opened 2023-04-02 13:20 UTC by hoseong511

## 개요

- 로그인/회원가입 화면 구현

## 작업사항
- 로그인/회원가입 화면
  - `CenterLayout` 위치에  라우터 `/signin` , `signup`추가 
  - `SignInLayout` 로그인/회원가입 화면 중앙 정렬을 위한 스타일
  - 입력창은 전부 placeholder로 처리함
- 로그인/회원가입 기능(빈칸확인)
  - 이벤트(onChange, onClick)를 이용해 state값 변경
  - 버튼 클릭시 모든 입력창 초기화 -> 타입을 전부 button 처리(초기화 방지)
  - 빈칸이면 `formCheck` state에 안내글 처리

2023-04-02 17:17 UTC, sumnii requested changes
뷰 구현 하시느라 고생하셨습니다! 깔끔하고 좋네요 ! :D

1. 현재 양쪽 사이드 사이에 끼인 상태로 로그인/회원가입 페이지가 구현되었는데 이에 대해서 처리를 고민해보셨는지 궁금합니다!
사실 제가 해당 화면을 고려하지 않고 App을 구현해둬서 구조 변경이 좀 어렵긴 한데, 그래도 시도해볼만한 부분이 아니었을까 생각되어요! 아무래도 어렵긴 하겠지만요 ㅠㅠ
처음 렌더링 하자마자 양쪽 사이드가 노출된 상태로 떠서 읭? 했었거든요 ㅎㅎ
(1) 구조 리팩토링
(2) css로 영역 넓히기
이렇게 두 가지 방법으로 로그인/회원가입을 단독 페이지로 사용할 수 있을 것 같은데,
1번은 저도 좀 고민해볼만한 부분인 것 같고 (좋은 생각이나 구조가 있다면 물론 리팩토링 하셔도 좋습니다!),
css로 단독 페이지로 만드는 방법을 한번 시도해보시면 css 사용에도 도움될 것 같아요!
두 가지 방법 다 어렵다고 생각되시면 제가 도움 드리겠습니다~!

2. 회원가입 페이지에서 ID 중복확인 버튼이 필요합니다!
슬랙방 확인하셨는지 모르겠지만, ID 겸 닉네임이라 중복확인 필요하고, 한글 사용 가능합니다!

그 외 리팩토링 가능한 부분이나, 오탈자가 보여서 suggestion 드렸어요~!
단순 제안이니 호쏭님 뜻대로 반영하시거나 다른 방식으로 수정하셔도 됩니다 :)

오탈자, ID 중복확인 버튼 추가하고 리뷰 재요청 주시면 감사하겠습니다!
1번은 이 브랜치 내에서 함께 수정하고 리뷰 재요청 하셔도 되고, 새 이슈로 파서 추후 PR 남기셔도 됩니다!

2023-04-02 17:17 UTC, sumnii commented on src/pages/signIn/SignIn.tsx
> +  }
`useState`와 `handler`를 엮어서 커스텀 훅을 만들어볼 수 있어요!
커스텀 훅은 저도 아직 어렵긴 한데, 나중에 리액트가 익숙해지면 리팩토링 해보시는걸 추천드려요 :)

2023-04-02 17:17 UTC, sumnii commented on src/pages/signIn/SignIn.tsx
> +  const [formCheck, setFormCheck] = React.useState("")
```suggestion
import React, { useState } from "react"
import { useNavigate } from "react-router-dom"
import * as S from "./style"

export default function signIn() {
  const navigate = useNavigate()
  const [idInput, setIdInput] = useState("")
  const [pwInput, setPwInput] = useState("")
  const [formCheck, setFormCheck] = useState("")
```

그리고 `useState()`는 직접 import해서 바로 사용하는게 더 좋아요!
자주 쓰이니까 계속 React로 접근해야하니 코드양이 제법 늘어날 거라.. ㅎㅎ

2023-04-02 17:17 UTC, sumnii commented on src/pages/signIn/style.jsx
> +  justify-content: spacee-between;
```suggestion
  justify-content: space-between;
```

오탈자가 있는데 원하는 대로 구현 되셨나요..?

2023-04-02 17:17 UTC, sumnii commented on src/pages/signUp/SignUp.tsx
> +  const [formCheck, setFormCheck] = React.useState("")
여기도 마찬가지로 직접 `useState` 임포트하면 한번의 임포트로 7개의 `React.` 생략!
그리고 커스텀 훅 리팩토링 가능한 부분!

2023-04-02 17:17 UTC, sumnii commented on src/pages/signUp/SignUp.tsx
> +        setFormCheck("인증번호가 틀립니다")
```suggestion
        setFormCheck("인증번호가 일치하지 않습니다.")
```

2023-04-02 21:27 UTC, hoseong511 commented on src/pages/signIn/style.jsx
> +  justify-content: spacee-between;
어쩐지 왜 의도대로 안되나 싶었습니다.. 찾아주셔서 김사합니다!

2023-04-02 21:36 UTC, hoseong511 commented on src/pages/signUp/SignUp.tsx
> +  const [formCheck, setFormCheck] = React.useState("")
확인했습니다!

2023-04-02 21:38 UTC, hoseong511 commented on src/pages/signIn/SignIn.tsx
> +  }
useState를 남발하면서 구현하는게 맞나 싶었거든요..! 커스텀훅으로 다시 해보겠습니다

2023-04-02 21:39 UTC, hoseong511 commented on src/pages/signIn/SignIn.tsx
> +  const [formCheck, setFormCheck] = React.useState("")
확인했습니다!

2023-04-03 04:27 UTC, hoseong511 commented
1. 사실 저는 파일의 구조를 바꾸지 않는 구현을 목표로 고민을 했었으나 잘 되지 않았습니다. 
그래서 구조를 바꾸지 않고 구현할 수 있는 방법에 대해서는 다음 TODO로 남겨둔 상태였고 제안해주신 첫 번째 방식으로 구조 리팩토링을 했습니다. 
구현부를 보시면 아시겠지만 Auth/UnAuth 파일에 전부 라우터가 들어가 있는 상태이고 이 부분은 좀 더 공부해서 보편적으로 사용되는 방식으로 바꾸겠습니다!

2. ID 중복확인은 화면을 누르거나 포커스가 이동할 때 확인하는 방식으로 넣어두었습니다.
넣어야지 생각만 하고 반영되지 않았었네요..

3. tsx로 변경했습니다..! 

여러 가지로 많이 배웁니다! 코드리뷰, `suggested change`, `main branch protection`, react, figma 등 정말 알차네요!

2023-04-03 06:06 UTC, sumnii requested changes
구조 리팩토링 쏘 깔끔! 👍🏻
제가 밖이라 코드만 보았는데 리팩토링 좋습니다!

근데 그 ID 중복확인은 서버에서 처리할거라 API 사용할 예정입니다..! ㅎㅎㅎ 버튼만 만들어두시면 될것 같아요 😂😂

그리구 useState() 남발해두 되구요!!
커스텀 훅은 음.. useState()로 input을 관리하면서 입력할때마다 입력값을 변경해서 렌더링하는!
이 반복되는 로직을 처리하기 위해서라서 useState와 + 입력 시의 핸들러함수를 합친거라고 생각하시면 됩니다~!~
저도 useState 잔뜩 남발해요 😂
요 부분은 그냥 귀찮음과 반복을 덜어주는거라 나중에 리팩토링 하셔도 되어요!👍🏻

중복확인 버튼(api 연동 예정)+불필요한 이벤트 삭제! 처리 부탁드리고 제가 집 가는대로 구현 확인 해볼게요 🙂

2023-04-03 06:35 UTC, hoseong511 commented
'불필요한 이벤트 -> 사용하지 않는 이벤트 함수의 매개변수' 로 이해하고 삭제 했습니다

2023-04-03 08:48 UTC, sumnii approved these changes
확인했습니다~~~~! good!
아 이번에 보니 타입 명시가 전혀 없던데, 이부분은 제가 eslint 룰 체크해서 강제하도록 할게요!
Eslinet 룰 적용되면 컴파일 시에 명시적으로 체크해주니까, 그 부분 다음에 수정하시면 될것 같아요!

2023-04-03 08:48 UTC, sumnii commented on src/pages/signUp/SignUp.tsx
> -    <S.SignInLayout onClick={onCheckIdHandler} onFocus={onCheckIdHandler}>
제가 말한 불필요한 이벤트는 요기였어요!
보여주셨던 영상처럼 구현되는것 보고싶었는데..금방 버튼 형식으로 수정하셨군요 😂

2023-04-03 08:48 UTC, merged

2023-04-03 08:51 UTC, hoseong511 commented on src/pages/signUp/SignUp.tsx
> -    <S.SignInLayout onClick={onCheckIdHandler} onFocus={onCheckIdHandler}>
이전 커밋으로 스위칭해서 확인 가능합니다!