27 fix 회원가입로그인 기능 관련 수정
4transcendence2/frontend pull request #28
Opened 2023-04-05 10:26 UTC by hoseong511

## 개요
- 회원가입/로그인 기능 수정

## 작업사항
- 회원가입/로그인 기능 수정
- 2차인증 주석처리

## 변경로직

2023-04-05 11:00 UTC, sumnii requested changes
2차인증이 없다지만, 로그인은 여전히 첫번째 시도때 바로 로그인 되지 않습니다! 분명 맞는 패스워드인데 확인하라고 나와요.. 이것도 같이 확인해주세요~!

2023-04-05 11:02 UTC, hoseong511 commented on src/pages/unAuth/signUp/SignUp.tsx
오 disable 속성 넣으면 되겠네요 감사합니다!

2023-04-05 11:05 UTC, sumnii commented on src/pages/unAuth/signIn/SignIn.tsx
그리고 여기 `authSecondHandler()` 함수에서 post할때 header는 필요 없지 않나요???

2023-04-05 11:05 UTC, hoseong511 commented on src/pages/unAuth/signUp/SignUp.tsx
로그인은 뭐가 문제일까요.. 혹시 괜찮으시다면 시도했던 아이디 비번 알려주실수 있나요..

2023-04-05 11:05 UTC, hoseong511 commented on src/pages/unAuth/signIn/SignIn.tsx
거기 명세서에는 안나와있는데 그걸 넣어줘야 응답이 옵니다!

2023-04-05 11:47 UTC, sumnii commented on src/pages/unAuth/signIn/SignIn.tsx
어머..명세서에서 누락 된거군요

2023-04-05 11:50 UTC, sumnii commented on src/pages/unAuth/signUp/SignUp.tsx
제가 잘못 친거 같기도...ㅎㅎㅎ..헿 죄송합니다

2023-04-05 12:04 UTC, sumnii commented on src/pages/unAuth/signUp/SignUp.tsx
아, 그리고! `accessToken` 같은거 카멜케이스로 변경해야 합니다~! 백엔드 업데이트 되었다면!

2023-04-05 12:25 UTC, hoseong511 commented on src/pages/unAuth/signUp/SignUp.tsx
아하 업데이트하겠습니다!

2023-04-06 04:54 UTC, sumnii requested changes
<img width="280" alt="image" src="https://user-images.githubusercontent.com/75291932/230275278-12ed20f8-f5e6-4c02-b0a8-c1fd3341699f.png">
인증 다 되었는데 제출 누르면 401 (Unauthorized) 뜹니다....!

2023-04-06 05:30 UTC, hoseong511 commented
아 맞네요.. ㅠ

2023-04-06 05:46 UTC, sumnii approved these changes

2023-04-06 05:46 UTC, merged