feat: 채팅방 관련 화면 개선 및 예외사항 처리 #42
4transcendence2/frontend pull request #44
Opened 2023-04-14 01:32 UTC by hoseong511

## 개요
- 채팅방 관련 개선 및 예외사항 처리

## 작업사항
- 채팅
  - 조회
    - `protected` 인 경우 자물쇠아이콘
    - 참여자수, 방장 데이터 연동
  - 비번방 입장
    - 비밀번호 입력 모달 추가
  - 채팅 화면
    - 오른쪽 참여자 목록 업데이트 연동
    - 스크롤 위치 조정  
  - 관련 이벤트들 chat.ts 로 이동
  - 응답값이 warning 및 error 인 경우 처리

## 변경로직

2023-04-14 06:18 UTC, sumnii requested changes
1. 들어가고 처음 입장할 때 채팅 내용이 보이지 않습니다. 슬랙으로 보낸 캡쳐처럼요!
여러번 테스트해보니 "본인이 만든 방에 처음으로 입장했을 때"의 경우인 것 같아요.
다음에 fix한 것과는 별개로 발생하는 버그합니다~!

2. 제 테스트의 경우 비공개방과 비밀번호방이 같은 2번방으로 들어가집니다.. 각 방 type마다 테이블이 다른가..? 왜 같은 roomId를 가질까요?

3. 비밀번호를 입력한 상태로 공개방으로 전환되면 해당 input이 막히지만, 기존의 input이 삭제되지는 않아서 이후 조건문에서도 걸리지 않고 서버로 전송되더라구요. 그래서 소켓 이벤트 결과로 계속 error를 만나서 콘솔에도 찍히지만, 유저 입장에서는 영문도 모른채 방이 안 만들어집니다..!

4. 비밀번호를 다르게 입력해도 방이 들어가집니다. -> 이건 approved를 준 서버의 문제인가요.?

5. 기본 폼으로 쓰이는 동일한 Modal 파일을 필요한 디렉토리마다 생성하여 사용하셨더라구요!
이 껍데기 Modal을 훅으로 만들고 모달 내용물을 삽입할 때 이 모달을 import해서 사용하면 좋을것 같습니다~! 중복되는 파일이 많아서요!

6. 디렉토리를 만들고 네이밍 할 때 "기능"보다 "컴포넌트"를 고려해주셨으면 좋겠습니당!
이전 PR의 코멘트와는 약간 다른 내용이기는 한데..
현재 `pages` 디렉토리에서 페이지를 기준으로 나눠져 있고, `chat`에 `chat/list`와 `chat/:chatId`로 나눠지므로 `chatList`와 `chatRoom`으로 나눠진건데 해당하는 페이지의 컴포넌트(방만들기 버튼, 나가기 버튼 등)는 각 포함되는 페이지에 맞게 하위로 들어가면 좋겠습니다!
안그래도 depth가 깊어지면서 chat/list (기존 chatList -> list 변경) 이런 식으로 중복되는 단어를 제거하고 리네이밍을 하려고 했는데, 호쏭님도 아마 너무 깊어질까봐 그냥 chat 안에 두신 것 같아요!
아니면 제가 이상적으로 생각하는 구조에 대해 제대로 설명을 드린 적이 없었던 것 같기도...
요렇게 구조 짜는거 어떻게 생각하시나요?

2023-04-14 06:24 UTC, hoseong511 commented on src/components/leftSide/profile/ProfileData.tsx
서버측에서 gameHistory를 안보내서요

2023-04-14 06:25 UTC, hoseong511 commented on src/socket/chat.ts
> +};
그거 수정했고 커밋만 올리면 됩니다

2023-04-14 07:02 UTC, sumnii commented on src/components/leftSide/profile/ProfileData.tsx
엥 빈 배열로 보내주기로 하셨었고, 제가 작업할 때까지만 해도 빈 배열로 받았었는데..? 혹시 제가 모르는 변경 사항이 있었을까요?

2023-04-14 07:04 UTC, sumnii commented on src/components/leftSide/profile/ProfileData.tsx
이거 서진님께 확인해볼게요!

2023-04-14 17:08 UTC, hoseong511 commented
1. createChatRoom 과정(백, 프론트)이 보완되어 정상 작동됩니다.
2, 4. roomId 를 확인하지 않아서 발생된 문제로 생각됩니다. 이 부분 roomId 조건을 확인하는 과정으로 수정 보완했습니다.
3. 채팅방의 상태(protected, public, private)이 바뀌면 비번 초기화 조건 추가했습니다.
5. 컴포넌트 centerHeader에 넣으면 될까요?
6. 디렉토리 구조 찬성합니다. 구현에 초점을 맞추다보니 우선순위가 낮았네요.. 다음부터 신경써서 하겠습니다.
  현재 디렉토리 구조에 컴포넌트에 맞게 이동시켜봤습니다. 이렇게 하면 될까요?

2023-04-15 06:06 UTC, sumnii commented
> 1 createChatRoom 과정(백, 프론트)이 보완되어 정상 작동됩니다.
2, 4 roomId 를 확인하지 않아서 발생된 문제로 생각됩니다. 이 부분 roomId 조건을 확인하는 과정으로 수정 보완했습니다. 

확인했는데, 약간의 오작동이 있습니다!
숨송과 아무개가 모두 공개방 11번에 있다가,
숨송은 그대로 11번에 있고 아무개는 퇴장 후 비번방 9번에 들어갔는데,
- 11번방의 참여자에 아무개가 추가되었습니다
- 11번방에 아무개가 입장했다는 알림은 없습니다
- 9번방에서 쓰는 아무개의 챗이 11번방에 보입니다
- 11번방에서 쓰는 숨송의 챗은 9번방에 보이지 않습니다

> 3 채팅방의 상태(protected, public, private)이 바뀌면 비번 초기화 조건 추가했습니다.

초기화되는 것은 확인했습니다!👍 그런데 비밀번호 틀린 경우에 아무 반응도 없습니다. 혹시 테스트 전 뭔가 조치를 취할게 있을까요?

> 5 컴포넌트 centerHeader에 넣으면 될까요?

모달 훅은 hooks에 넣어주시면 됩니당!!

> 6 디렉토리 구조 찬성합니다. 구현에 초점을 맞추다보니 우선순위가 낮았네요.. 다음부터 신경써서 하겠습니다. 현재 디렉토리 구조에 컴포넌트에 맞게 이동시켜봤습니다. 이렇게 하면 될까요?

너무 좋습니다! 제가 줄줄이 길게 쓴 디렉토리명도 제 작업 시에 수정해두겠습니다!

2023-04-15 06:10 UTC, sumnii commented
여전히 `roomId`가 뭔가 꼬이는 것 같군요 ㅠㅠ
우선 "개선"에 대한 부분은 해결된 것 같아서, 원하신다면 채팅 관련 fix 이슈 새로 파서 작업하셔도 됩니다!
의견 주시면 머지하거나 그대로 두거나 할게요!

2023-04-15 06:28 UTC, sumnii commented
3번 이슈 +a는 이슈 #45 PR #46 로 분리~!

2023-04-15 06:28 UTC, merged