feat: 친구 추가 및 채팅 초대 #79
4transcendence2/frontend pull request #83
Opened 2023-04-25 09:36 UTC by hoseong511

## 개요
- 친구 추가, 리스트
- 채팅 초대, 알림

## 작업사항
- 친구추가는 구독 방식(친구 취소 기능 x)
- 채팅초대는 채팅방 안에서 친구에게 사용하는 기능
  - 해당 채팅 방에 방장, 관리자만 사용할 수 있는 기능
  - 수락여부 없이 채팅에 참여
- 채팅초대되면 알림 발생 -> 알림 누르면 해당 채팅방으로 이동

2023-04-25 11:48 UTC, sumnii requested changes
발견버그1
<img width="823" alt="image" src="https://user-images.githubusercontent.com/75291932/234265729-37f231e5-5593-4779-9e3a-f959be8ef9d0.png">
초대했을 때, 초대한 사람이 보고 있는 방의 참여자 리스트는 업데이트 되지 않음

발견버그2
오프라인 상대 초대 -> 초대받은 사람 로그인 -> 알림을 받을 수 없음
: 프론트나 백에서 오프라인 상대는 초대 안되도록 처리하는게 좋을 것 같은데 어떨까요?

발견버그3
<img width="198" alt="image" src="https://user-images.githubusercontent.com/75291932/234266589-d1f1658c-9828-4b35-8be7-16a7d00f321c.png">
방장의 경우 친구 리스트에서도 채팅 관련 oper 노출
: 요거 혹시 코드가 좀 지저분해서 수정하기 어려우시면 제가 할게요..! 나중에 리팩토링 하려다가 너무 복잡해져서 손을 못대고 있습니다 ..ㅎㅎ

제가 지금 dm에서 굉장히 늪에 여러번 빠지고 있어서, 우선 로직만 테스트 해보았어요!
버그 수정되면 코드 다시 꼼꼼히 보겠습니다! :)

2023-04-25 12:00 UTC, hoseong511 commented
> 발견버그1 <img alt="image" width="823" src="https://user-images.githubusercontent.com/75291932/234265729-37f231e5-5593-4779-9e3a-f959be8ef9d0.png"> 초대했을 때, 초대한 사람이 보고 있는 방의 참여자 리스트는 업데이트 되지 않음

이 경우는 서진님이 현재 처리 중이신 작업이 업데이트 되면 말씀드리겠습니다.

> 발견버그2 오프라인 상대 초대 -> 초대받은 사람 로그인 -> 알림을 받을 수 없음 : 프론트나 백에서 오프라인 상대는 초대 안되도록 처리하는게 좋을 것 같은데 어떨까요?

로그인 상태 반영하겠습니다. 감사합니다!

> 발견버그3 <img alt="image" width="198" src="https://user-images.githubusercontent.com/75291932/234266589-d1f1658c-9828-4b35-8be7-16a7d00f321c.png"> 방장의 경우 친구 리스트에서도 채팅 관련 oper 노출 : 요거 혹시 코드가 좀 지저분해서 수정하기 어려우시면 제가 할게요..! 나중에 리팩토링 하려다가 너무 복잡해져서 손을 못대고 있습니다 ..ㅎㅎ

이건 어제 숨송님 작업 브랜치 봤을 때, 드롭메뉴(친구리스트) 대한 권한 처리가 되어 있어서 일부러 냅두었는데 다시 추가하도록 할께요

2023-04-27 04:24 UTC, hoseong511 commented
- login:boolean -> status:string 으로 반영
- 초대시, status === login 인 경우만 팝업창(게임 중인 경우는 팝업 x)
- `chatInvitation` 은 로그아웃을 하지 않는 이상 unsub하지 않도록 처리

2023-04-27 04:46 UTC, hoseong511 commented on src/components/rightSide/MyProfile.tsx
> +  const { showNotiModal, NotiModal, onOpenNotiModal, newNoti } = useNotiModal(profileQuery?.data?.status);
이게 누락되어 있었네요

2023-04-27 05:10 UTC, sumnii approved these changes
확인했습니다! 고생하셨어요!
테스트하면서 발견한 이 기능 외적인 에러들은 따로 이슈로 정리해둘게요!

각 코멘트에 적긴 했지만 크게 제안드리는 점은
1. box-sizing: border-box 속성 유지
2. 구독/구독해제 콘솔 로그 유지 (err가 아닌 경우에도!) -> 테스트 하면서 확인한 에러의 경우에도 구독 확인이 필요합니다!!

이렇게 두가지입니다! 고민해보시고 의견 주세요!

2023-04-27 05:10 UTC, sumnii commented on src/pages/auth/Auth.tsx
이 부분은 빌드 전까지 이전 상태로 유지하는게 좋을것 같아요!
아직 전체 구현이 끝나지 않아서 구독/해제 상태 모니터링이 필요할 것 같습니다!

2023-04-27 05:10 UTC, sumnii commented on src/pages/auth/chat/list/JoinBtn.tsx
> +        setNotice(res.detail);
`입장이 거부된 방입니다.`
멘트 적용 부탁드립니다~!

2023-04-27 05:17 UTC, sumnii commented on src/components/rightSide/MyProfile.tsx
> +  const { showNotiModal, NotiModal, onOpenNotiModal, newNoti } = useNotiModal(profileQuery?.data?.status);
앗 리뷰 작성중이었는데 먼저 수정하셨군요 ...!ㅋㅋㅌㅋㅌㅋㅋㅋ

2023-04-27 05:27 UTC, hoseong511 commented on src/index.css
>    /* -webkit-appearance: none; */
제가 맞춰놓은 input 크기들이 일괄적으로 이상해져서 저렇게 처리했습니다. 나름 주어진 조건에서 이리저리 값 바꿔가면서 심혈을 기울여 만들어 놓은것들이라서요.
전역 스타일을 바꾸신다면 미리 알려주셨으면 좋겠네요
근데 이 부분에 있어 이전 pr에서 언급 하셨던 적이 있었나요? 있었다면 죄송요

2023-04-27 05:28 UTC, hoseong511 commented on src/pages/auth/Auth.tsx
네 반영해둘게요

2023-04-27 05:28 UTC, hoseong511 commented on src/pages/auth/chat/list/JoinBtn.tsx
> +        setNotice(res.detail);
넵

2023-04-27 05:30 UTC, hoseong511 commented on src/components/rightSide/user/InviteBtn.tsx
네

2023-04-27 05:37 UTC, sumnii commented on src/index.css
>    /* -webkit-appearance: none; */
아 죄송합니다..제가 생각이 짧았네요
박스 사이징 변경으로 변화가 생긴 부분이 있다면 제가 수정해두도록 하겠습니다

2023-04-27 05:38 UTC, sumnii commented on src/components/rightSide/user/InviteBtn.tsx
아 그럼 `alert()` 부분에 대해서만 조건문을 걸어서 처리하는건 어떨까요?
내키지 않으신다면 그냥 두어도 됩니다

2023-04-27 05:40 UTC, hoseong511 commented on src/components/rightSide/user/InviteBtn.tsx
추후 리팩토링할때 반영할께요

2023-04-27 05:42 UTC, hoseong511 commented on src/index.css
>    /* -webkit-appearance: none; */
아뇨 제가 할게요

2023-04-27 06:33 UTC, merged